import { registerIframeAudioHandler } from '@/iframe_server/audio';
import { registerIframeCharacterHandler } from '@/iframe_server/character';
import { registerIframeChatMessageHandler } from '@/iframe_server/chat_message';
import { registerIframeDisplayedMessageHandler } from '@/iframe_server/displayed_message';
import { registerIframeFrontendVersionHandler } from '@/iframe_server/frontend_version';
import { registerIframeGenerateHandler } from '@/iframe_server/generate';
import { registerIframeLorebookHandler } from '@/iframe_server/lorebook';
import { registerIframeLorebookEntryHandler } from '@/iframe_server/lorebook_entry';
import { registerIframeSlashHandler } from '@/iframe_server/slash';
import { registerIframeTavernRegexHandler } from '@/iframe_server/tavern_regex';
import { registerIframeUtilHandler } from '@/iframe_server/util';
import { registerIframeVariableHandler } from '@/iframe_server/variables';

registerIframeChatMessageHandler();
registerIframeDisplayedMessageHandler();
registerIframeFrontendVersionHandler();
registerIframeGenerateHandler();
registerIframeLorebookEntryHandler();
registerIframeLorebookHandler();
registerIframeSlashHandler();
registerIframeTavernRegexHandler();
registerIframeUtilHandler();
registerIframeVariableHandler();
registerIframeCharacterHandler();
registerIframeAudioHandler();
