import { world_names } from '@sillytavern/scripts/world-info';

/**
 * Reloads the editor with the specified world info file
 * @param file The file to load in the editor
 * @param loadIfNotSelected Indicates whether to load the file even if it's not currently selected
 */
export function reloadEditor(file: string, load_if_not_selected: boolean = false) {
  const current_index = Number($('#world_editor_select').val());
  const selected_index = world_names.indexOf(file);
  if (selected_index !== -1 && (load_if_not_selected || current_index === selected_index)) {
    $('#world_editor_select').val(selected_index).trigger('change');
  }
}

export const reloadEditorDebounced = _.debounce(reloadEditor, 1000);

export const settingsToUpdate = {
  chat_completion_source: ['#chat_completion_source', 'chat_completion_source', false, true],
  temperature: ['#temp_openai', 'temp_openai', false, false],
  frequency_penalty: ['#freq_pen_openai', 'freq_pen_openai', false, false],
  presence_penalty: ['#pres_pen_openai', 'pres_pen_openai', false, false],
  top_p: ['#top_p_openai', 'top_p_openai', false, false],
  top_k: ['#top_k_openai', 'top_k_openai', false, false],
  top_a: ['#top_a_openai', 'top_a_openai', false, false],
  min_p: ['#min_p_openai', 'min_p_openai', false, false],
  repetition_penalty: ['#repetition_penalty_openai', 'repetition_penalty_openai', false, false],
  max_context_unlocked: ['#oai_max_context_unlocked', 'max_context_unlocked', true, false],
  openai_model: ['#model_openai_select', 'openai_model', false, true],
  claude_model: ['#model_claude_select', 'claude_model', false, true],
  openrouter_model: ['#model_openrouter_select', 'openrouter_model', false, true],
  openrouter_use_fallback: ['#openrouter_use_fallback', 'openrouter_use_fallback', true, true],
  openrouter_group_models: ['#openrouter_group_models', 'openrouter_group_models', false, true],
  openrouter_sort_models: ['#openrouter_sort_models', 'openrouter_sort_models', false, true],
  openrouter_providers: ['#openrouter_providers_chat', 'openrouter_providers', false, true],
  openrouter_allow_fallbacks: ['#openrouter_allow_fallbacks', 'openrouter_allow_fallbacks', true, true],
  openrouter_middleout: ['#openrouter_middleout', 'openrouter_middleout', false, true],
  ai21_model: ['#model_ai21_select', 'ai21_model', false, true],
  mistralai_model: ['#model_mistralai_select', 'mistralai_model', false, true],
  cohere_model: ['#model_cohere_select', 'cohere_model', false, true],
  perplexity_model: ['#model_perplexity_select', 'perplexity_model', false, true],
  groq_model: ['#model_groq_select', 'groq_model', false, true],
  nanogpt_model: ['#model_nanogpt_select', 'nanogpt_model', false, true],
  deepseek_model: ['#model_deepseek_select', 'deepseek_model', false, true],
  aimlapi_model: ['#model_aimlapi_select', 'aimlapi_model', false, true],
  zerooneai_model: ['#model_01ai_select', 'zerooneai_model', false, true],
  xai_model: ['#model_xai_select', 'xai_model', false, true],
  pollinations_model: ['#model_pollinations_select', 'pollinations_model', false, true],
  custom_model: ['#custom_model_id', 'custom_model', false, true],
  custom_url: ['#custom_api_url_text', 'custom_url', false, true],
  custom_include_body: ['#custom_include_body', 'custom_include_body', false, true],
  custom_exclude_body: ['#custom_exclude_body', 'custom_exclude_body', false, true],
  custom_include_headers: ['#custom_include_headers', 'custom_include_headers', false, true],
  custom_prompt_post_processing: ['#custom_prompt_post_processing', 'custom_prompt_post_processing', false, true],
  google_model: ['#model_google_select', 'google_model', false, true],
  vertexai_model: ['#model_vertexai_select', 'vertexai_model', false, true],
  openai_max_context: ['#openai_max_context', 'openai_max_context', false, false],
  openai_max_tokens: ['#openai_max_tokens', 'openai_max_tokens', false, false],
  wrap_in_quotes: ['#wrap_in_quotes', 'wrap_in_quotes', true, false],
  names_behavior: ['#names_behavior', 'names_behavior', false, false],
  send_if_empty: ['#send_if_empty_textarea', 'send_if_empty', false, false],
  impersonation_prompt: ['#impersonation_prompt_textarea', 'impersonation_prompt', false, false],
  new_chat_prompt: ['#newchat_prompt_textarea', 'new_chat_prompt', false, false],
  new_group_chat_prompt: ['#newgroupchat_prompt_textarea', 'new_group_chat_prompt', false, false],
  new_example_chat_prompt: ['#newexamplechat_prompt_textarea', 'new_example_chat_prompt', false, false],
  continue_nudge_prompt: ['#continue_nudge_prompt_textarea', 'continue_nudge_prompt', false, false],
  bias_preset_selected: ['#openai_logit_bias_preset', 'bias_preset_selected', false, false],
  reverse_proxy: ['#openai_reverse_proxy', 'reverse_proxy', false, true],
  wi_format: ['#wi_format_textarea', 'wi_format', false, false],
  scenario_format: ['#scenario_format_textarea', 'scenario_format', false, false],
  personality_format: ['#personality_format_textarea', 'personality_format', false, false],
  group_nudge_prompt: ['#group_nudge_prompt_textarea', 'group_nudge_prompt', false, false],
  stream_openai: ['#stream_toggle', 'stream_openai', true, false],
  prompts: ['', 'prompts', false, false],
  prompt_order: ['', 'prompt_order', false, false],
  show_external_models: ['#openai_show_external_models', 'show_external_models', true, true],
  proxy_password: ['#openai_proxy_password', 'proxy_password', false, true],
  assistant_prefill: ['#claude_assistant_prefill', 'assistant_prefill', false, false],
  assistant_impersonation: ['#claude_assistant_impersonation', 'assistant_impersonation', false, false],
  claude_use_sysprompt: ['#claude_use_sysprompt', 'claude_use_sysprompt', true, false],
  use_makersuite_sysprompt: ['#use_makersuite_sysprompt', 'use_makersuite_sysprompt', true, false],
  vertexai_auth_mode: ['#vertexai_auth_mode', 'vertexai_auth_mode', false, true],
  vertexai_region: ['#vertexai_region', 'vertexai_region', false, true],
  vertexai_express_project_id: ['#vertexai_express_project_id', 'vertexai_express_project_id', false, true],
  squash_system_messages: ['#squash_system_messages', 'squash_system_messages', true, false],
  image_inlining: ['#openai_image_inlining', 'image_inlining', true, false],
  inline_image_quality: ['#openai_inline_image_quality', 'inline_image_quality', false, false],
  video_inlining: ['#openai_video_inlining', 'video_inlining', true, false],
  continue_prefill: ['#continue_prefill', 'continue_prefill', true, false],
  continue_postfix: ['#continue_postfix', 'continue_postfix', false, false],
  function_calling: ['#openai_function_calling', 'function_calling', true, false],
  show_thoughts: ['#openai_show_thoughts', 'show_thoughts', true, false],
  reasoning_effort: ['#openai_reasoning_effort', 'reasoning_effort', false, false],
  enable_web_search: ['#openai_enable_web_search', 'enable_web_search', true, false],
  seed: ['#seed_openai', 'seed', false, false],
  n: ['#n_openai', 'n', false, false],
  bypass_status_check: ['#openai_bypass_status_check', 'bypass_status_check', true, true],
  request_images: ['#openai_request_images', 'request_images', true, false],
  extensions: ['#NULL_SELECTOR', 'extensions', false, false],
};
